# -*- coding: utf-8 -*-
"""conversion to ncnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxnL4ZiSDuLrtYf0XlE4Lepil9bMiNY3
"""

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Install Ultralytics YOLO
!pip install ultralytics

# Step 2: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 3: Navigate to the directory where your model is stored
# %cd /content/drive/MyDrive/  # Change this path if needed

# Step 4: Convert final_best.pt to NCNN format
!yolo export model=final_best.pt format=ncnn

# Step 5: Rename the output folder to 'ncnn_model'
!mv runs/exports ncnn_model

# Step 3: Convert the model to NCNN using the full path
!yolo export model=/content/drive/MyDrive/final_best.pt format=ncnn